### ISSUE TITLE
LICENSE mismatch

### ISSUE THREAD

**Issue by job** [cloudflare/rpki-rtr-client#2]
It appears the 3-Clause BSD license was put into `LICENSE`, however the `MIT` license is referenced in `setup.py`

See https://github.com/cloudflare/rpki-rtr-client/blob/master/LICENSE where github identifies it as BSD rather than MIT.

**Comment by mahtin** [comment]
Fixed in https://github.com/cloudflare/rpki-rtr-client/commit/ced1ec6aa29931d93ecbfc2fcc2d2c993ab08e68
