### ISSUE TITLE
python3 ./setup.py install doesn't result in CLI hooks in the $PATH

### ISSUE THREAD

**Issue by job** [cloudflare/rpki-rtr-client#3]
The project should probably be packaged in such a way that it can be distributed via PyPi.

`python3 ./setup.py install` should result in `rpki-rtr-client` ending up somewhere in one of the `$PATH` locations.

See https://github.com/job/aggregate6/blob/master/setup.py#L78-L79 for an example

**Comment by mahtin** [comment]
Fixed by @oskar456 and released in 1.1.3 (sorry for the delay)
